Calculating Sigmoid using numpy

In [1]:
import numpy as np
import math

In [2]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    
    return s

In [3]:
basic_sigmoid(5)

0.9933071490757153

In [4]:
#example pf np.exp
x = np.array([1,2,3])
print(np.exp(x)) # result is (exp(1).exp(2),exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [5]:
def basic_sigmoid(x):
    s = 1/(1+np.exp(-x))
    
    return s

In [6]:
x=  np.array([1,2,3])
basic_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

### 1.2 - Sigmoid gradient

We will need to compute gradients to optimize loss functions using backpropagation. Let's code our first gradient function.

**Exercise**: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
You often code this function in two steps:
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
2. Compute $\sigma'(x) = s(1-s)$

In [7]:

#Formula = s(1-s) s=sigmoid function
a=1-basic_sigmoid(x)
b=basic_sigmoid(x)
print("sigmoid derivative: ",a*b)




sigmoid derivative:  [0.19661193 0.10499359 0.04517666]


In [9]:
def image2vector(image):
    image=image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return image;

In [10]:

image = np.array([[[ 0.67826139, 0.29380381],
[0.90714982, 0.52835647],
[0.4215251, 0.45017551]],
                  
[[0.92814219, 0.96677647],
[0.85304703, 0.52351845],
[0.19981397, 0.27417313]],

[[0.68659855, 0.00533165],
[0.10828313, 0.49978937],
[0.34144279, 0.94636077]]])

print("image2shape: ",str(image2vector(image)))

image2shape:  [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.68659855]
 [0.00533165]
 [0.10828313]
 [0.49978937]
 [0.34144279]
 [0.94636077]]


## Normalisation

In [14]:
def normalizationRows(x):
    x_norm = np.linalg.norm(x,axis=True,keepdims=True)
    x=x/x_norm
    return x

In [15]:
x=np.array([[0,1000,4],[2,6,4]])
print("normalization(x",str(normalizationRows(x)))

normalization(x [[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


## Broadcasting and softmax function

In [12]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    x=x_exp/x_sum
    return x

In [13]:
x=np.array([
            [1,2,3,4,5],
            [6,7,8,9,10]
            ])
print("softmax: ",softmax(x))

softmax:  [[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
 [0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]]


## Vectorisation

In [11]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### Classic dot product of vectors implementation
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i] * x2[i]
toc = time.process_time()
print("dot = " + str(dot) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic outer product implementation 
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i, j] = x1[i] * x2[j]
toc = time.process_time()
print("outer = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic elementwise implementation
tic = time.process_time() 
mul = np.zeros(len(x1))
for i in range(len(x1)): 
    mul[i] =  x1[1] * x2[i]
toc = time.process_time()
print("elementwise multiplication = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic general dot product implementation
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time() 
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print("gdot = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms") 


dot = 278
 --- Computation time = 0.10500000000002174ms


outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [15]:
### Vectorised dot product
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " + str(dot) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised outer product
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("outer = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised elementwise multiplication
tic = time.process_time() 
mul = np.multiply(x1,x2)
toc = time.process_time()
print("elementwise multiplication = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised general dot product
tic = time.process_time() 
dot = np.dot(W,x1)
toc = time.process_time()
print("gdot = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms") 

dot = 278
 --- Computation time = 0.10799999999999699ms


outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 --- Computation time = 0.14799999999992597ms


elementwise multiplication = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25